apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backfill-redis-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backfill-redis-1-0-gamma
    app.kubernetes.io/part-of: rekor-1-0-gamma
  name: backfill-redis-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: backfill-redis-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: backfill-redis-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/backfill-redis-1-0-gamma@sha256:9a8ab70162a2aac1e8335fc1d82c84cd177a95c4ab820fa00dc915c07a25eb76
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
