apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-server-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-server-1-0-gamma
    app.kubernetes.io/part-of: rekor-1-0-gamma
  name: rekor-server-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-server-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-server-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/rekor-server-1-0-gamma@sha256:53b650ad487dce78025d1dbddc5f25116c132f4e78b7d6f8c1dd0638574f6db3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
