apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backfill-redis-1-0-gamma
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/backfill-redis-1-0-gamma@sha256:946495fbf7695dad29b59f8a0d7f438128bfd0a61f3c0426eeb3eff834c82fdc
        name: container-image
        resources: {}
status: {}
