apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backfill-redis-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backfill-redis-1-0-gamma
    app.kubernetes.io/part-of: rekor-1-0-gamma
  name: backfill-redis-1-0-gammaqpne
spec:
  port:
    targetPort: 6379
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backfill-redis-1-0-gamma
    weight: 100
status: {}
