apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-search-ui-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/rekor-search-ui-1-0-gamma@sha256:ea4344bc762809ca46ea0708de378d8592b97194a9c1e08eb9396294276818bf
        name: container-image
        resources: {}
status: {}
